apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: customer-profile
  namespace: mae
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: customer-profile
    apis.apps.tanzu.vmware.com/register-api: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    no-sonar: "true"
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "11"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: scanning_source_policy
      value: lax-scan-policy
    - name: scanning_image_policy
      value: lax-scan-policy
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: test
        apps.tanzu.vmware.com/language: java
    - name: api_descriptor
      value:
        type: openapi
        location: 
          path: "/api-docs"
        owner: team-awesome
        system: tanzu-gtt
        description: Manage customer profiles
    - name: gitops_ssh_secret
      value: git-auth
  source:
    git:
      url: ssh://git@github.com/Mpluya/prep-java-rest-service
      ref:
        branch: main
  serviceClaims:
    - name: postgres-db
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ClassClaim
        name: customer-database
